channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=23.3.1
- pip:
  - mlflow==2.15.1
  - cloudpickle==3.0.0
  - numpy==1.26.3
  - psutil==5.9.8
  - scikit-learn==1.4.0
  - scipy==1.12.0
name: mlflow-env
